name: mobiking
description: "A new Flutter project."
publish_to: 'none'
version: 9.3.1+15

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  get: ^4.6.6
  share_plus: ^7.2.1
  pin_code_fields: ^8.0.1
  dio: ^5.8.0+1
  mockito: ^5.4.2
  build_runner: ^2.4.6
  get_storage: ^2.1.1
  flutter_svg: ^1.1.6
  shimmer: ^3.0.0
  intl:
  razorpay_flutter: ^1.3.7  # Use specific version instead of latest
  uuid: ^4.4.0
  lottie: ^3.3.1
  connectivity_plus: ^5.0.2
  audioplayers: ^6.0.0
  animated_milestone: ^0.0.2
  like_button: ^2.0.5
  firebase_core: ^2.13.1
  firebase_messaging: ^14.6.0
  cloud_firestore: ^4.8.0
  cached_network_image: ^3.3.1
  url_launcher:
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  permission_handler: ^11.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.6
  flutter_html: ^3.0.0-beta.2
  fluttertoast: ^8.2.8
  pdf: ^3.10.8
  printing: ^5.12.0
  flutter_markdown: ^0.6.18



  flutter_launcher_icons: ^0.13.1
  flutter_rating_bar: ^4.0.1
  workmanager:


dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/svg/home.svg
    - assets/svg/category.svg
    - assets/svg/cart.svg
    - assets/svg/profile.svg
    - assets/images/
    - assets/svg/
    - assets/animations/
    - assets/sounds/pop.mp3

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Light.otf
          weight: 300
        - asset: assets/fonts/Gilroy-ExtraBold.otf
          weight: 800

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_main.png"